### ISSUE TITLE
Jacaranda and Redbud Saplings Rendering Issue in flower pots.

### ISSUE THREAD

**Issue by KajesLorian** [teamauroramods/Abundance-Forge#1]
Forge-1.16.4-35.1.36
Abundance-1.16.4-1.0.0
Jacaranda and Redbud Saplings both have black backgrounds when placed in flower pots. No issues when placed on grass blocks.

![2021-03-01_12 01 00](https://user-images.githubusercontent.com/16963626/109531589-1915d680-7a86-11eb-8d60-76f889d93992.png)

**Comment by ex0planetary** [comment]
Huh, thought I patched this for this mod but I must've not. Will fix shortly.

**Comment by ex0planetary** [comment]
Unable to reproduce the bug. Do you have OptiFine installed? That's the only thing I can think of that could be causing this, since I'm setting the render layers properly.

**Comment by KajesLorian** [comment]
I do not. Here's a list of my current mods.

https://pastebin.com/3yVBxYec

**Comment by ex0planetary** [comment]
Try reinstalling the mod. I'm not having any issues myself and I'm making the saplings the same way Mojang makes them so if you're having issues with just this mod's sapling something must've broken on your end.

If that doesn't fix it I don't think there's any way I can really help you here, because it's definitely another mod's problem.
