### ISSUE TITLE
Saguaro cactus doesn't generate in terraforged's badland variant (bryce)

### ISSUE THREAD

**Issue by Firch** [teamauroramods/Abundance-Forge#43]
In `terraforged:bryce` biome only vanilla cactuses are present. Saguaro cactuses still can generate in terraforged world in vanilla badlands variants, so this is a single biome issue rather than generation issue.
![badlands](https://user-images.githubusercontent.com/47253246/122284034-9e72a900-cf06-11eb-8ce1-27280510aa39.gif)

**Comment by Brun333rp** [comment]
saguaro cacti have been removed from Abundance

**Comment by ex0planetary** [comment]
^^^

Also, Terraforged compat could probably come but it's super low on the priority list since afaik none of the team really likes it all that much. If you want some better terrain that plays well with vanilla+ mods check out [Simply Improved Terrain](https://www.curseforge.com/minecraft/mc-mods/simply-improved-terrain).
